import uuid
from datetime import datetime
from decimal import Decimal
from enum import StrEnum

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.shared.models import (
    Base,
    CompanyScopedMixin,
    Money,
    SyncTrackedMixin,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
    sync_index,
)


class PaymentKind(StrEnum):
    CASH = "CASH"
    EWALLET = "EWALLET"  # GCash, Maya
    CARD = "CARD"
    BANK = "BANK"
    OTHER = "OTHER"


class PaymentMethod(
    UUIDPrimaryKeyMixin, CompanyScopedMixin, TimestampMixin, SyncTrackedMixin, Base
):
    """A way of paying. The POS only *records* e-wallet/card payments (reference number); the
    actual terminal or app is a separate device, so recording works offline."""

    __tablename__ = "payment_methods"
    __table_args__ = (
        UniqueConstraint("company_id", "code"),
        CheckConstraint("kind IN ('CASH', 'EWALLET', 'CARD', 'BANK', 'OTHER')", name="kind"),
        sync_index("payment_methods"),
    )

    code: Mapped[str] = mapped_column(String(16))
    name: Mapped[str] = mapped_column(String(50))
    kind: Mapped[PaymentKind] = mapped_column(String(16))
    requires_reference: Mapped[bool] = mapped_column(Boolean, server_default=text("false"))
    opens_drawer: Mapped[bool] = mapped_column(Boolean, server_default=text("false"))
    sort_order: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    is_active: Mapped[bool] = mapped_column(Boolean, server_default=text("true"))


# code -> (name, kind, requires_reference, opens_drawer)
DEFAULT_PAYMENT_METHODS: dict[str, tuple[str, PaymentKind, bool, bool]] = {
    "CASH": ("Cash", PaymentKind.CASH, False, True),
    "GCASH": ("GCash", PaymentKind.EWALLET, True, False),
    "MAYA": ("Maya", PaymentKind.EWALLET, True, False),
    "CARD": ("Card", PaymentKind.CARD, True, False),
    "BANK_TRANSFER": ("Bank transfer", PaymentKind.BANK, True, False),
}


class PaymentStatus(StrEnum):
    CAPTURED = "CAPTURED"
    VOIDED = "VOIDED"


class Payment(UUIDPrimaryKeyMixin, CompanyScopedMixin, Base):
    """Money received for a sale. `id` is generated by the POS (offline-origin)."""

    __tablename__ = "payments"
    __table_args__ = (
        CheckConstraint("amount > 0", name="amount_positive"),
        CheckConstraint("change_amount >= 0", name="change_non_negative"),
        CheckConstraint("status IN ('CAPTURED', 'VOIDED')", name="status"),
    )

    sale_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("sales.id", ondelete="RESTRICT"), index=True
    )
    payment_method_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("payment_methods.id"))
    method_kind: Mapped[PaymentKind] = mapped_column(String(16))  # snapshot for reports
    amount: Mapped[Decimal] = mapped_column(Money)  # applied to the sale
    tendered: Mapped[Decimal | None] = mapped_column(Money)
    change_amount: Mapped[Decimal] = mapped_column(Money, server_default=text("0"))
    reference_no: Mapped[str | None] = mapped_column(String(100))
    status: Mapped[PaymentStatus] = mapped_column(
        String(16), server_default=PaymentStatus.CAPTURED.value
    )
    occurred_at: Mapped[datetime]
    received_at: Mapped[datetime] = mapped_column(server_default=func.now())
