/** Permission codes used by the admin portal (subset of backend `P`, users/permissions.py). */
export const ADMIN_PERM = {
  PRODUCTS_READ: "products.read",
  PRODUCTS_WRITE: "products.write",
  PRICES_WRITE: "prices.write",
  INVENTORY_READ: "inventory.read",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_COUNT: "inventory.count",
  INVENTORY_TRANSFER: "inventory.transfer",
  SUPPLIERS_MANAGE: "suppliers.manage",
  PURCHASING_MANAGE: "purchasing.manage",
  PURCHASING_RECEIVE: "purchasing.receive",
  CUSTOMERS_READ: "customers.read",
  CUSTOMERS_WRITE: "customers.write",
  PROMOTIONS_MANAGE: "promotions.manage",
  SALES_VIEW: "sales.view",
  SALES_VOID: "sales.void",
  RETURNS_CREATE: "returns.create",
  EXPENSES_MANAGE: "expenses.manage",
  REPORTS_VIEW: "reports.view",
  REPORTS_FINANCIAL: "reports.financial",
  REVIEW_FLAGS_MANAGE: "review_flags.manage",
  SYNC_MONITOR: "sync.monitor",
  SETTINGS_MANAGE: "settings.manage",
} as const;
