import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { evaluatePromotions, isEligible, localClock, type PromoDef, type PromoLine } from "./evaluate";

// Generated by backend/scripts/gen_promotion_vectors.py; pytest checks the same file.
const VECTORS_PATH = resolve(__dirname, "../../../shared/test-vectors/promotions.json");

interface RawLine {
  line_id: string;
  variant_id: string;
  product_id: string;
  category_id: string | null;
  brand_id: string | null;
  quantity: string;
  unit_price: string;
}
interface Case {
  name: string;
  now: string;
  promotions: PromoDef[];
  manual_discount_lines?: string[];
  expected: { line_id: string; promotion_id: string; discount: string }[];
}
interface Vectors {
  branch_id: string;
  lines: RawLine[];
  cases: Case[];
}

const vectors = JSON.parse(readFileSync(VECTORS_PATH, "utf-8")) as Vectors;

function lines(manual: string[] = []): PromoLine[] {
  return vectors.lines.map((l) => ({
    lineId: l.line_id,
    variantId: l.variant_id,
    productId: l.product_id,
    categoryId: l.category_id,
    brandId: l.brand_id,
    quantity: l.quantity,
    unitPrice: l.unit_price,
    hasManualDiscount: manual.includes(l.line_id),
  }));
}

describe("shared promotion vectors", () => {
  it("has cases", () => expect(vectors.cases.length).toBeGreaterThan(5));

  for (const c of vectors.cases) {
    it(c.name, () => {
      const applied = evaluatePromotions(lines(c.manual_discount_lines), c.promotions, {
        now: new Date(c.now),
        timeZone: "Asia/Manila",
        branchId: vectors.branch_id,
      });
      expect(applied.map((a) => ({ line_id: a.lineId, promotion_id: a.promotionId, discount: a.discount }))).toEqual(
        c.expected,
      );
    });
  }
});

describe("eligibility details", () => {
  const base: PromoDef = { id: "p", kind: "PERCENT_OFF", value: "10", targets: [{ type: "ALL" }] };

  it("uses the branch time zone, not the device's", () => {
    // 2026-09-27 23:30 UTC = Monday 07:30 in Manila (Sunday in UTC)
    const now = new Date("2026-09-27T23:30:00Z");
    expect(localClock(now, "Asia/Manila")).toEqual({ isoWeekday: 1, seconds: 7 * 3600 + 30 * 60 });
    expect(isEligible({ ...base, days_of_week: [1] }, now, "Asia/Manila", "b")).toBe(true);
    expect(isEligible({ ...base, days_of_week: [7] }, now, "Asia/Manila", "b")).toBe(false);
  });

  it("treats a window ending before it starts as spanning midnight", () => {
    const promo = { ...base, start_time: "22:00:00", end_time: "02:00:00" };
    expect(isEligible(promo, new Date("2026-09-28T01:00:00+08:00"), "Asia/Manila", "b")).toBe(true);
    expect(isEligible(promo, new Date("2026-09-28T03:00:00+08:00"), "Asia/Manila", "b")).toBe(false);
  });
});
