"""company features and onboarding

Revision ID: 8f9e3d20bc71
Revises: fbaf8685d085
Create Date: 2026-09-26 08:37:38.742528+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8f9e3d20bc71"
down_revision: str | Sequence[str] | None = "fbaf8685d085"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "features",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "companies", sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###
    # Businesses that already exist are set up: only new sign-ups get the onboarding wizard.
    # Their features stay as they were (no stored choices = everything on).
    op.execute("UPDATE companies SET onboarding_completed_at = now()")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "onboarding_completed_at")
    op.drop_column("companies", "features")
    # ### end Alembic commands ###
