"""storefront online catalog

Revision ID: 5f5a4551ceb3
Revises: e1c3cb7b756c
Create Date: 2026-09-26 05:51:10.392869+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5f5a4551ceb3"
down_revision: str | Sequence[str] | None = "e1c3cb7b756c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storefronts",
        sa.Column("slug", sa.String(length=48), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "branch_ids",
            sa.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column(
            "stock_display", sa.String(length=16), server_default="AVAILABILITY", nullable=False
        ),
        sa.Column(
            "low_stock_threshold",
            sa.Numeric(precision=14, scale=3),
            server_default=sa.text("5"),
            nullable=False,
        ),
        sa.Column("show_prices", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("allow_indexing", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("about", sa.String(length=1000), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("messenger_url", sa.String(length=300), nullable=True),
        sa.Column("hours", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "low_stock_threshold >= 0", name=op.f("ck_storefronts_low_stock_threshold_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_storefronts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storefronts")),
        sa.UniqueConstraint("company_id", name=op.f("uq_storefronts_company_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_storefronts_slug")),
    )
    op.create_index(op.f("ix_storefronts_company_id"), "storefronts", ["company_id"], unique=False)
    op.add_column(
        "products",
        sa.Column("show_online", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index(
        "ix_products_online",
        "products",
        ["company_id", "name"],
        unique=False,
        postgresql_where=sa.text("show_online AND is_active"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_products_online",
        table_name="products",
        postgresql_where=sa.text("show_online AND is_active"),
    )
    op.drop_column("products", "show_online")
    op.drop_index(op.f("ix_storefronts_company_id"), table_name="storefronts")
    op.drop_table("storefronts")
    # ### end Alembic commands ###
