"""catalog and inventory ledger

Revision ID: 1e3cfbdadecb
Revises: ef8f6c10c69c
Create Date: 2026-09-25 22:10:07.420871+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.shared import ddl

revision: str = "1e3cfbdadecb"
down_revision: str | Sequence[str] | None = "ef8f6c10c69c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SYNC_TRACKED = [
    "categories",
    "brands",
    "units",
    "tax_rates",
    "price_levels",
    "products",
    "product_units",
    "product_variants",
    "barcodes",
    "prices",
    "inventory_balances",
]
APPEND_ONLY = ["inventory_movements"]

# Frozen defaults for companies that existed before this migration. New companies are seeded
# by the application (app.modules.catalog_defaults).
UNITS = [
    ("PC", "Piece", False),
    ("PACK", "Pack", False),
    ("BOX", "Box", False),
    ("CASE", "Case", False),
    ("DOZEN", "Dozen", False),
    ("KG", "Kilogram", True),
    ("G", "Gram", True),
    ("L", "Liter", True),
    ("ML", "Milliliter", True),
    ("M", "Meter", True),
]
TAX_RATES = [
    ("VAT12", "VAT 12%", "12.000", "VATABLE", True),
    ("VAT_EXEMPT", "VAT Exempt", "0.000", "EXEMPT", False),
    ("ZERO_RATED", "Zero-rated", "0.000", "ZERO_RATED", False),
]
PRICE_LEVELS = [("RETAIL", "Retail", True, 0), ("WHOLESALE", "Wholesale", False, 1)]


def _backfill_defaults() -> None:
    for code, name, allows_decimal in UNITS:
        op.execute(
            sa.text(
                "INSERT INTO units (id, company_id, code, name, allows_decimal) "
                "SELECT gen_random_uuid(), id, :code, :name, :dec FROM companies "
                "ON CONFLICT DO NOTHING"
            ).bindparams(code=code, name=name, dec=allows_decimal)
        )
    for code, name, rate, kind, is_default in TAX_RATES:
        op.execute(
            sa.text(
                "INSERT INTO tax_rates (id, company_id, code, name, rate, kind, is_default) "
                "SELECT gen_random_uuid(), id, :code, :name, CAST(:rate AS numeric), :kind, :dflt "
                "FROM companies ON CONFLICT DO NOTHING"
            ).bindparams(code=code, name=name, rate=rate, kind=kind, dflt=is_default)
        )
    for code, name, is_default, sort_order in PRICE_LEVELS:
        op.execute(
            sa.text(
                "INSERT INTO price_levels (id, company_id, code, name, is_default, sort_order) "
                "SELECT gen_random_uuid(), id, :code, :name, :dflt, :sort FROM companies "
                "ON CONFLICT DO NOTHING"
            ).bindparams(code=code, name=name, dflt=is_default, sort=sort_order)
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_brands_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
    )
    op.create_index(op.f("ix_brands_company_id"), "brands", ["company_id"], unique=False)
    op.create_index("ix_brands_company_sync", "brands", ["company_id", "sync_txid"], unique=False)
    op.create_index(
        "uq_brands_company_name_lower",
        "brands",
        ["company_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_table(
        "categories",
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_categories_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint(
            "company_id",
            "parent_id",
            "name",
            name=op.f("uq_categories_company_id_parent_id_name"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_categories_company_id"), "categories", ["company_id"], unique=False)
    op.create_index(
        "ix_categories_company_sync", "categories", ["company_id", "sync_txid"], unique=False
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "document_sequences",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=64), server_default=sa.text("''"), nullable=False),
        sa.Column("doc_type", sa.String(length=32), nullable=False),
        sa.Column("next_value", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_document_sequences_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_sequences")),
        sa.UniqueConstraint(
            "company_id",
            "scope",
            "doc_type",
            name=op.f("uq_document_sequences_company_id_scope_doc_type"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "price_levels",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_price_levels_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_levels")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_price_levels_company_id_code")),
    )
    op.create_index(
        op.f("ix_price_levels_company_id"), "price_levels", ["company_id"], unique=False
    )
    op.create_index(
        "ix_price_levels_company_sync", "price_levels", ["company_id", "sync_txid"], unique=False
    )
    op.create_index(
        "uq_price_levels_default_per_company",
        "price_levels",
        ["company_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "tax_rates",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("rate", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('VATABLE', 'EXEMPT', 'ZERO_RATED')", name=op.f("ck_tax_rates_kind")
        ),
        sa.CheckConstraint("rate >= 0 AND rate < 100", name=op.f("ck_tax_rates_rate_range")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_tax_rates_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_rates")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_tax_rates_company_id_code")),
    )
    op.create_index(op.f("ix_tax_rates_company_id"), "tax_rates", ["company_id"], unique=False)
    op.create_index(
        "ix_tax_rates_company_sync", "tax_rates", ["company_id", "sync_txid"], unique=False
    )
    op.create_table(
        "units",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("allows_decimal", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_units_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_units_company_id_code")),
    )
    op.create_index(op.f("ix_units_company_id"), "units", ["company_id"], unique=False)
    op.create_index("ix_units_company_sync", "units", ["company_id", "sync_txid"], unique=False)
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("brand_id", sa.Uuid(), nullable=True),
        sa.Column("base_unit_id", sa.Uuid(), nullable=False),
        sa.Column("tax_rate_id", sa.Uuid(), nullable=False),
        sa.Column("track_inventory", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_unit_id"], ["units.id"], name=op.f("fk_products_base_unit_id_units")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_products_brand_id_brands"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_products_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tax_rate_id"], ["tax_rates.id"], name=op.f("fk_products_tax_rate_id_tax_rates")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_brand_id"), "products", ["brand_id"], unique=False)
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(op.f("ix_products_company_id"), "products", ["company_id"], unique=False)
    op.create_index(
        "ix_products_company_sync", "products", ["company_id", "sync_txid"], unique=False
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_table(
        "product_units",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("factor", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("is_base", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "NOT is_base OR factor = 1", name=op.f("ck_product_units_base_factor_one")
        ),
        sa.CheckConstraint("factor > 0", name=op.f("ck_product_units_factor_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_product_units_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_units_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_product_units_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_units")),
        sa.UniqueConstraint(
            "product_id", "unit_id", name=op.f("uq_product_units_product_id_unit_id")
        ),
    )
    op.create_index(
        op.f("ix_product_units_company_id"), "product_units", ["company_id"], unique=False
    )
    op.create_index(
        "ix_product_units_company_sync", "product_units", ["company_id", "sync_txid"], unique=False
    )
    op.create_index(
        op.f("ix_product_units_product_id"), "product_units", ["product_id"], unique=False
    )
    op.create_index(
        "uq_product_units_base_per_product",
        "product_units",
        ["product_id"],
        unique=True,
        postgresql_where=sa.text("is_base"),
    )
    op.create_table(
        "product_variants",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "average_cost",
            sa.Numeric(precision=14, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("last_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("reorder_point", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "average_cost >= 0", name=op.f("ck_product_variants_average_cost_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_product_variants_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
        sa.UniqueConstraint("company_id", "sku", name=op.f("uq_product_variants_company_id_sku")),
    )
    op.create_index(
        op.f("ix_product_variants_company_id"), "product_variants", ["company_id"], unique=False
    )
    op.create_index(
        "ix_product_variants_company_sync",
        "product_variants",
        ["company_id", "sync_txid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variants_product_id"), "product_variants", ["product_id"], unique=False
    )
    op.create_index(
        "uq_product_variants_default_per_product",
        "product_variants",
        ["product_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "review_flags",
        sa.Column("flag_type", sa.String(length=32), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("stock_location_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("occurrences", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="OPEN", nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_by_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('OPEN', 'RESOLVED', 'DISMISSED')", name=op.f("ck_review_flags_status")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_review_flags_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_review_flags_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"], ["users.id"], name=op.f("fk_review_flags_resolved_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["stock_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_review_flags_stock_location_id_stock_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_flags")),
    )
    op.create_index(
        op.f("ix_review_flags_company_id"), "review_flags", ["company_id"], unique=False
    )
    op.create_index(
        "ix_review_flags_company_status", "review_flags", ["company_id", "status"], unique=False
    )
    op.create_index(
        "uq_review_flags_open_subject",
        "review_flags",
        ["company_id", "flag_type", "entity_type", "entity_id", "stock_location_id"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "barcodes",
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("symbology", sa.String(length=20), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_barcodes_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_unit_id"],
            ["product_units.id"],
            name=op.f("fk_barcodes_product_unit_id_product_units"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_barcodes_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_barcodes")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_barcodes_company_id_code")),
    )
    op.create_index(op.f("ix_barcodes_company_id"), "barcodes", ["company_id"], unique=False)
    op.create_index(
        "ix_barcodes_company_sync", "barcodes", ["company_id", "sync_txid"], unique=False
    )
    op.create_index(op.f("ix_barcodes_variant_id"), "barcodes", ["variant_id"], unique=False)
    op.create_table(
        "inventory_balances",
        sa.Column("stock_location_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "quantity",
            sa.Numeric(precision=14, scale=3),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("last_movement_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_inventory_balances_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_inventory_balances_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stock_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_inventory_balances_stock_location_id_stock_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_inventory_balances_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint(
            "stock_location_id", "variant_id", name=op.f("pk_inventory_balances")
        ),
    )
    op.create_index(
        "ix_inventory_balances_branch", "inventory_balances", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_balances_company_id"), "inventory_balances", ["company_id"], unique=False
    )
    op.create_index(
        "ix_inventory_balances_company_sync",
        "inventory_balances",
        ["company_id", "sync_txid"],
        unique=False,
    )
    op.create_table(
        "inventory_movements",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("stock_location_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("direction", sa.SmallInteger(), nullable=False),
        sa.Column(
            "signed_quantity",
            sa.Numeric(precision=14, scale=3),
            sa.Computed("quantity * direction", persisted=True),
            nullable=False,
        ),
        sa.Column("movement_type", sa.String(length=24), nullable=False),
        sa.Column("reference_type", sa.String(length=32), nullable=True),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "movement_type IN ('INITIAL_STOCK', 'PURCHASE', 'PURCHASE_RETURN', 'SALE', 'SALE_RETURN', 'SALE_VOID', 'TRANSFER_OUT', 'TRANSFER_IN', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'DAMAGED', 'EXPIRED', 'STOCK_COUNT')",
            name=op.f("ck_inventory_movements_movement_type"),
        ),
        sa.CheckConstraint("direction IN (1, -1)", name=op.f("ck_inventory_movements_direction")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_inventory_movements_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_inventory_movements_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_inventory_movements_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_inventory_movements_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_inventory_movements_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["stock_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_inventory_movements_stock_location_id_stock_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_inventory_movements_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_inventory_movements_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
    )
    op.create_index(
        op.f("ix_inventory_movements_branch_id"), "inventory_movements", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_movements_company_id"),
        "inventory_movements",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_company_occurred",
        "inventory_movements",
        ["company_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_product_id"),
        "inventory_movements",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_reference",
        "inventory_movements",
        ["reference_type", "reference_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_variant_location",
        "inventory_movements",
        ["variant_id", "stock_location_id"],
        unique=False,
    )
    op.create_table(
        "prices",
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("price_level_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "min_quantity",
            sa.Numeric(precision=14, scale=3),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("min_quantity > 0", name=op.f("ck_prices_min_quantity_positive")),
        sa.CheckConstraint("price >= 0", name=op.f("ck_prices_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_prices_branch_id_branches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_prices_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["price_level_id"],
            ["price_levels.id"],
            name=op.f("fk_prices_price_level_id_price_levels"),
        ),
        sa.ForeignKeyConstraint(
            ["product_unit_id"],
            ["product_units.id"],
            name=op.f("fk_prices_product_unit_id_product_units"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_prices_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prices")),
        sa.UniqueConstraint(
            "variant_id",
            "product_unit_id",
            "price_level_id",
            "branch_id",
            "min_quantity",
            name=op.f("uq_prices_variant_id_product_unit_id_price_level_id_branch_id_min_quantity"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_prices_company_id"), "prices", ["company_id"], unique=False)
    op.create_index("ix_prices_company_sync", "prices", ["company_id", "sync_txid"], unique=False)
    op.create_index(op.f("ix_prices_variant_id"), "prices", ["variant_id"], unique=False)
    # ### end Alembic commands ###

    for table in SYNC_TRACKED:
        op.execute(ddl.sync_trigger(table))
    for table in APPEND_ONLY:
        op.execute(ddl.append_only_trigger(table))
    _backfill_defaults()


def downgrade() -> None:
    for table in APPEND_ONLY:
        op.execute(ddl.drop_append_only_trigger(table))
    for table in SYNC_TRACKED:
        op.execute(ddl.drop_sync_trigger(table))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prices_variant_id"), table_name="prices")
    op.drop_index("ix_prices_company_sync", table_name="prices")
    op.drop_index(op.f("ix_prices_company_id"), table_name="prices")
    op.drop_table("prices")
    op.drop_index("ix_inventory_movements_variant_location", table_name="inventory_movements")
    op.drop_index("ix_inventory_movements_reference", table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_product_id"), table_name="inventory_movements")
    op.drop_index("ix_inventory_movements_company_occurred", table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_company_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_branch_id"), table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index("ix_inventory_balances_company_sync", table_name="inventory_balances")
    op.drop_index(op.f("ix_inventory_balances_company_id"), table_name="inventory_balances")
    op.drop_index("ix_inventory_balances_branch", table_name="inventory_balances")
    op.drop_table("inventory_balances")
    op.drop_index(op.f("ix_barcodes_variant_id"), table_name="barcodes")
    op.drop_index("ix_barcodes_company_sync", table_name="barcodes")
    op.drop_index(op.f("ix_barcodes_company_id"), table_name="barcodes")
    op.drop_table("barcodes")
    op.drop_index(
        "uq_review_flags_open_subject",
        table_name="review_flags",
        postgresql_where=sa.text("status = 'OPEN'"),
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index("ix_review_flags_company_status", table_name="review_flags")
    op.drop_index(op.f("ix_review_flags_company_id"), table_name="review_flags")
    op.drop_table("review_flags")
    op.drop_index(
        "uq_product_variants_default_per_product",
        table_name="product_variants",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_index(op.f("ix_product_variants_product_id"), table_name="product_variants")
    op.drop_index("ix_product_variants_company_sync", table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_company_id"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(
        "uq_product_units_base_per_product",
        table_name="product_units",
        postgresql_where=sa.text("is_base"),
    )
    op.drop_index(op.f("ix_product_units_product_id"), table_name="product_units")
    op.drop_index("ix_product_units_company_sync", table_name="product_units")
    op.drop_index(op.f("ix_product_units_company_id"), table_name="product_units")
    op.drop_table("product_units")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index("ix_products_company_sync", table_name="products")
    op.drop_index(op.f("ix_products_company_id"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index(op.f("ix_products_brand_id"), table_name="products")
    op.drop_table("products")
    op.drop_index("ix_units_company_sync", table_name="units")
    op.drop_index(op.f("ix_units_company_id"), table_name="units")
    op.drop_table("units")
    op.drop_index("ix_tax_rates_company_sync", table_name="tax_rates")
    op.drop_index(op.f("ix_tax_rates_company_id"), table_name="tax_rates")
    op.drop_table("tax_rates")
    op.drop_index(
        "uq_price_levels_default_per_company",
        table_name="price_levels",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_index("ix_price_levels_company_sync", table_name="price_levels")
    op.drop_index(op.f("ix_price_levels_company_id"), table_name="price_levels")
    op.drop_table("price_levels")
    op.drop_table("document_sequences")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index("ix_categories_company_sync", table_name="categories")
    op.drop_index(op.f("ix_categories_company_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index("uq_brands_company_name_lower", table_name="brands")
    op.drop_index("ix_brands_company_sync", table_name="brands")
    op.drop_index(op.f("ix_brands_company_id"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###
