"""customers returns promotions

Revision ID: 428f5d187452
Revises: 34f69fa13fd1
Create Date: 2026-09-25 22:45:39.707533+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.shared import ddl

SYNC_TRACKED = ["customers", "promotions"]

revision: str = "428f5d187452"
down_revision: str | Sequence[str] | None = "34f69fa13fd1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotions",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "value", sa.Numeric(precision=14, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("buy_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("get_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column(
            "min_quantity",
            sa.Numeric(precision=14, scale=3),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "targets",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("days_of_week", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("branch_ids", postgresql.ARRAY(sa.Uuid()), nullable=True),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "kind <> 'BUY_X_GET_Y' OR (buy_quantity > 0 AND get_quantity > 0)",
            name=op.f("ck_promotions_bxgy_quantities"),
        ),
        sa.CheckConstraint(
            "kind IN ('PERCENT_OFF', 'AMOUNT_OFF', 'FIXED_PRICE', 'BUY_X_GET_Y')",
            name=op.f("ck_promotions_kind"),
        ),
        sa.CheckConstraint("value >= 0", name=op.f("ck_promotions_value_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_promotions_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotions")),
    )
    op.create_index(op.f("ix_promotions_company_id"), "promotions", ["company_id"], unique=False)
    op.create_index(
        "ix_promotions_company_sync", "promotions", ["company_id", "sync_txid"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("code", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("tin", sa.String(length=32), nullable=True),
        sa.Column("price_level_id", sa.Uuid(), nullable=True),
        sa.Column("credit_limit", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_on_device_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_customers_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_on_device_id"],
            ["devices.id"],
            name=op.f("fk_customers_created_on_device_id_devices"),
        ),
        sa.ForeignKeyConstraint(
            ["price_level_id"],
            ["price_levels.id"],
            name=op.f("fk_customers_price_level_id_price_levels"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(op.f("ix_customers_company_id"), "customers", ["company_id"], unique=False)
    op.create_index("ix_customers_company_name", "customers", ["company_id", "name"], unique=False)
    op.create_index(
        "ix_customers_company_phone", "customers", ["company_id", "phone"], unique=False
    )
    op.create_index(
        "ix_customers_company_sync", "customers", ["company_id", "sync_txid"], unique=False
    )
    op.create_table(
        "returns",
        sa.Column("original_sale_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("stock_location_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("cash_session_id", sa.Uuid(), nullable=True),
        sa.Column("return_number", sa.String(length=40), nullable=False),
        sa.Column("cashier_id", sa.Uuid(), nullable=False),
        sa.Column("authorized_by_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("refund_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["authorized_by_id"], ["users.id"], name=op.f("fk_returns_authorized_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_returns_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["cash_session_id"],
            ["cash_sessions.id"],
            name=op.f("fk_returns_cash_session_id_cash_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["cashier_id"], ["users.id"], name=op.f("fk_returns_cashier_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_returns_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_returns_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["original_sale_id"], ["sales.id"], name=op.f("fk_returns_original_sale_id_sales")
        ),
        sa.ForeignKeyConstraint(
            ["stock_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_returns_stock_location_id_stock_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_returns")),
    )
    op.create_index(op.f("ix_returns_branch_id"), "returns", ["branch_id"], unique=False)
    op.create_index(op.f("ix_returns_company_id"), "returns", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_returns_original_sale_id"), "returns", ["original_sale_id"], unique=False
    )
    op.create_table(
        "refunds",
        sa.Column("return_id", sa.Uuid(), nullable=False),
        sa.Column("payment_method_id", sa.Uuid(), nullable=False),
        sa.Column("method_kind", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reference_no", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_refunds_amount_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_refunds_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
            name=op.f("fk_refunds_payment_method_id_payment_methods"),
        ),
        sa.ForeignKeyConstraint(
            ["return_id"],
            ["returns.id"],
            name=op.f("fk_refunds_return_id_returns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds")),
    )
    op.create_index(op.f("ix_refunds_company_id"), "refunds", ["company_id"], unique=False)
    op.create_index(op.f("ix_refunds_return_id"), "refunds", ["return_id"], unique=False)
    op.create_table(
        "return_items",
        sa.Column("return_id", sa.Uuid(), nullable=False),
        sa.Column("sale_item_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("refund_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("restock", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_return_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_return_items_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["return_id"],
            ["returns.id"],
            name=op.f("fk_return_items_return_id_returns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sale_item_id"],
            ["sale_items.id"],
            name=op.f("fk_return_items_sale_item_id_sale_items"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_return_items_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_return_items")),
    )
    op.create_index(
        op.f("ix_return_items_company_id"), "return_items", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_return_items_return_id"), "return_items", ["return_id"], unique=False)
    op.create_index(
        op.f("ix_return_items_sale_item_id"), "return_items", ["sale_item_id"], unique=False
    )
    op.add_column("sale_items", sa.Column("promotion_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_sale_items_promotion_id_promotions"),
        "sale_items",
        "promotions",
        ["promotion_id"],
        ["id"],
    )
    op.create_index(op.f("ix_sales_customer_id"), "sales", ["customer_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_sales_customer_id_customers"), "sales", "customers", ["customer_id"], ["id"]
    )
    # ### end Alembic commands ###

    for table in SYNC_TRACKED:
        op.execute(ddl.sync_trigger(table))


def downgrade() -> None:
    for table in SYNC_TRACKED:
        op.execute(ddl.drop_sync_trigger(table))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_sales_customer_id_customers"), "sales", type_="foreignkey")
    op.drop_index(op.f("ix_sales_customer_id"), table_name="sales")
    op.drop_constraint(
        op.f("fk_sale_items_promotion_id_promotions"), "sale_items", type_="foreignkey"
    )
    op.drop_column("sale_items", "promotion_id")
    op.drop_index(op.f("ix_return_items_sale_item_id"), table_name="return_items")
    op.drop_index(op.f("ix_return_items_return_id"), table_name="return_items")
    op.drop_index(op.f("ix_return_items_company_id"), table_name="return_items")
    op.drop_table("return_items")
    op.drop_index(op.f("ix_refunds_return_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_company_id"), table_name="refunds")
    op.drop_table("refunds")
    op.drop_index(op.f("ix_returns_original_sale_id"), table_name="returns")
    op.drop_index(op.f("ix_returns_company_id"), table_name="returns")
    op.drop_index(op.f("ix_returns_branch_id"), table_name="returns")
    op.drop_table("returns")
    op.drop_index("ix_customers_company_sync", table_name="customers")
    op.drop_index("ix_customers_company_phone", table_name="customers")
    op.drop_index("ix_customers_company_name", table_name="customers")
    op.drop_index(op.f("ix_customers_company_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index("ix_promotions_company_sync", table_name="promotions")
    op.drop_index(op.f("ix_promotions_company_id"), table_name="promotions")
    op.drop_table("promotions")
    # ### end Alembic commands ###
