"""sales payments cash sessions sync

Revision ID: 43cc34f6bf79
Revises: 1e3cfbdadecb
Create Date: 2026-09-25 22:24:26.881600+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.shared import ddl

SYNC_TRACKED = ["payment_methods", "cash_sessions", "sales"]

# Frozen defaults for companies created before this migration (new ones are seeded by the app).
PAYMENT_METHODS = [
    ("CASH", "Cash", "CASH", False, True, 0),
    ("GCASH", "GCash", "EWALLET", True, False, 1),
    ("MAYA", "Maya", "EWALLET", True, False, 2),
    ("CARD", "Card", "CARD", True, False, 3),
    ("BANK_TRANSFER", "Bank transfer", "BANK", True, False, 4),
]


revision: str = "43cc34f6bf79"
down_revision: str | Sequence[str] | None = "1e3cfbdadecb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "requires_reference", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("opens_drawer", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('CASH', 'EWALLET', 'CARD', 'BANK', 'OTHER')",
            name=op.f("ck_payment_methods_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payment_methods_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_methods")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_payment_methods_company_id_code")),
    )
    op.create_index(
        op.f("ix_payment_methods_company_id"), "payment_methods", ["company_id"], unique=False
    )
    op.create_index(
        "ix_payment_methods_company_sync",
        "payment_methods",
        ["company_id", "sync_txid"],
        unique=False,
    )
    op.create_table(
        "cash_sessions",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("opened_by_id", sa.Uuid(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opening_float", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="OPEN", nullable=False),
        sa.Column("closed_by_id", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("counted_cash", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("expected_cash", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("over_short", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("server_expected_cash", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("closing_note", sa.String(length=500), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("status IN ('OPEN', 'CLOSED')", name=op.f("ck_cash_sessions_status")),
        sa.CheckConstraint(
            "opening_float >= 0", name=op.f("ck_cash_sessions_opening_float_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_cash_sessions_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_id"], ["users.id"], name=op.f("fk_cash_sessions_closed_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_cash_sessions_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_cash_sessions_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_id"], ["users.id"], name=op.f("fk_cash_sessions_opened_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_sessions")),
    )
    op.create_index(
        op.f("ix_cash_sessions_branch_id"), "cash_sessions", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_cash_sessions_company_id"), "cash_sessions", ["company_id"], unique=False
    )
    op.create_index(
        "ix_cash_sessions_company_sync", "cash_sessions", ["company_id", "sync_txid"], unique=False
    )
    op.create_index(
        "ix_cash_sessions_device_opened", "cash_sessions", ["device_id", "opened_at"], unique=False
    )
    op.create_table(
        "sync_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=48), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("client_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_sync_operations_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_sync_operations_device_id_devices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_operations")),
    )
    op.create_index(
        op.f("ix_sync_operations_company_id"), "sync_operations", ["company_id"], unique=False
    )
    op.create_index(
        "ix_sync_operations_device_received",
        "sync_operations",
        ["device_id", "received_at"],
        unique=False,
    )
    op.create_index(
        "ix_sync_operations_entity", "sync_operations", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "cash_movements",
        sa.Column("cash_session_id", sa.Uuid(), nullable=False),
        sa.Column("movement_type", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("authorized_by_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "movement_type IN ('CASH_IN', 'CASH_OUT', 'PICKUP')",
            name=op.f("ck_cash_movements_movement_type"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_cash_movements_amount_positive")),
        sa.ForeignKeyConstraint(
            ["authorized_by_id"],
            ["users.id"],
            name=op.f("fk_cash_movements_authorized_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["cash_session_id"],
            ["cash_sessions.id"],
            name=op.f("fk_cash_movements_cash_session_id_cash_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_cash_movements_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cash_movements_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_movements")),
    )
    op.create_index(
        op.f("ix_cash_movements_cash_session_id"),
        "cash_movements",
        ["cash_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cash_movements_company_id"), "cash_movements", ["company_id"], unique=False
    )
    op.create_table(
        "sales",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("stock_location_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("cash_session_id", sa.Uuid(), nullable=True),
        sa.Column("receipt_number", sa.String(length=40), nullable=False),
        sa.Column("cashier_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("price_level_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="COMPLETED", nullable=False),
        sa.Column("prices_include_tax", sa.Boolean(), nullable=False),
        sa.Column("gross_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_discount_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("order_discount_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("paid_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("change_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("vatable_sales", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("vat_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("exempt_sales", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("zero_rated_sales", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("order_discount_kind", sa.String(length=16), nullable=True),
        sa.Column("order_discount_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("order_discount_reason", sa.String(length=200), nullable=True),
        sa.Column("order_discount_authorized_by_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("totals_mismatch", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_by_id", sa.Uuid(), nullable=True),
        sa.Column("void_authorized_by_id", sa.Uuid(), nullable=True),
        sa.Column("void_reason", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("sync_txid", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("status IN ('COMPLETED', 'VOIDED')", name=op.f("ck_sales_status")),
        sa.CheckConstraint("total >= 0", name=op.f("ck_sales_total_non_negative")),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_sales_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["cash_session_id"],
            ["cash_sessions.id"],
            name=op.f("fk_sales_cash_session_id_cash_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["cashier_id"], ["users.id"], name=op.f("fk_sales_cashier_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_sales_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_sales_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["order_discount_authorized_by_id"],
            ["users.id"],
            name=op.f("fk_sales_order_discount_authorized_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["price_level_id"],
            ["price_levels.id"],
            name=op.f("fk_sales_price_level_id_price_levels"),
        ),
        sa.ForeignKeyConstraint(
            ["stock_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_sales_stock_location_id_stock_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["void_authorized_by_id"],
            ["users.id"],
            name=op.f("fk_sales_void_authorized_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_id"], ["users.id"], name=op.f("fk_sales_voided_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
        sa.UniqueConstraint(
            "device_id", "receipt_number", name=op.f("uq_sales_device_id_receipt_number")
        ),
    )
    op.create_index("ix_sales_branch_occurred", "sales", ["branch_id", "occurred_at"], unique=False)
    op.create_index(op.f("ix_sales_cash_session_id"), "sales", ["cash_session_id"], unique=False)
    op.create_index(op.f("ix_sales_cashier_id"), "sales", ["cashier_id"], unique=False)
    op.create_index(op.f("ix_sales_company_id"), "sales", ["company_id"], unique=False)
    op.create_index(
        "ix_sales_company_occurred",
        "sales",
        ["company_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index("ix_sales_company_sync", "sales", ["company_id", "sync_txid"], unique=False)
    op.create_index(
        "ix_sales_receipt_number", "sales", ["company_id", "receipt_number"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("payment_method_id", sa.Uuid(), nullable=False),
        sa.Column("method_kind", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tendered", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "change_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("reference_no", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="CAPTURED", nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("status IN ('CAPTURED', 'VOIDED')", name=op.f("ck_payments_status")),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.CheckConstraint("change_amount >= 0", name=op.f("ck_payments_change_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payments_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
            name=op.f("fk_payments_payment_method_id_payment_methods"),
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"], ["sales.id"], name=op.f("fk_payments_sale_id_sales"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_company_id"), "payments", ["company_id"], unique=False)
    op.create_index(op.f("ix_payments_sale_id"), "payments", ["sale_id"], unique=False)
    op.create_table(
        "sale_items",
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("unit_factor", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("unit_code", sa.String(length=16), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("variant_name", sa.String(length=200), nullable=True),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("barcode", sa.String(length=64), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("original_unit_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("price_overridden_by_id", sa.Uuid(), nullable=True),
        sa.Column("discount_kind", sa.String(length=16), nullable=True),
        sa.Column("discount_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("discount_reason", sa.String(length=200), nullable=True),
        sa.Column("discount_authorized_by_id", sa.Uuid(), nullable=True),
        sa.Column("gross", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_discount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("order_discount_share", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("net", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_rate_id", sa.Uuid(), nullable=True),
        sa.Column("tax_rate", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("tax_kind", sa.String(length=16), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sale_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_sale_items_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["discount_authorized_by_id"],
            ["users.id"],
            name=op.f("fk_sale_items_discount_authorized_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["price_overridden_by_id"],
            ["users.id"],
            name=op.f("fk_sale_items_price_overridden_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_sale_items_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["product_unit_id"],
            ["product_units.id"],
            name=op.f("fk_sale_items_product_unit_id_product_units"),
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"], ["sales.id"], name=op.f("fk_sale_items_sale_id_sales"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tax_rate_id"], ["tax_rates.id"], name=op.f("fk_sale_items_tax_rate_id_tax_rates")
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_sale_items_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_items")),
        sa.UniqueConstraint("sale_id", "line_no", name=op.f("uq_sale_items_sale_id_line_no")),
    )
    op.create_index(op.f("ix_sale_items_company_id"), "sale_items", ["company_id"], unique=False)
    op.create_index("ix_sale_items_variant", "sale_items", ["variant_id"], unique=False)
    # ### end Alembic commands ###

    for table in SYNC_TRACKED:
        op.execute(ddl.sync_trigger(table))
    for code, name, kind, ref, drawer, sort in PAYMENT_METHODS:
        op.execute(
            sa.text(
                "INSERT INTO payment_methods "
                "(id, company_id, code, name, kind, requires_reference, opens_drawer, sort_order) "
                "SELECT gen_random_uuid(), id, :code, :name, :kind, :ref, :drawer, :sort "
                "FROM companies ON CONFLICT DO NOTHING"
            ).bindparams(code=code, name=name, kind=kind, ref=ref, drawer=drawer, sort=sort)
        )


def downgrade() -> None:
    for table in SYNC_TRACKED:
        op.execute(ddl.drop_sync_trigger(table))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sale_items_variant", table_name="sale_items")
    op.drop_index(op.f("ix_sale_items_company_id"), table_name="sale_items")
    op.drop_table("sale_items")
    op.drop_index(op.f("ix_payments_sale_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_company_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_sales_receipt_number", table_name="sales")
    op.drop_index("ix_sales_company_sync", table_name="sales")
    op.drop_index("ix_sales_company_occurred", table_name="sales")
    op.drop_index(op.f("ix_sales_company_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_cashier_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_cash_session_id"), table_name="sales")
    op.drop_index("ix_sales_branch_occurred", table_name="sales")
    op.drop_table("sales")
    op.drop_index(op.f("ix_cash_movements_company_id"), table_name="cash_movements")
    op.drop_index(op.f("ix_cash_movements_cash_session_id"), table_name="cash_movements")
    op.drop_table("cash_movements")
    op.drop_index("ix_sync_operations_entity", table_name="sync_operations")
    op.drop_index("ix_sync_operations_device_received", table_name="sync_operations")
    op.drop_index(op.f("ix_sync_operations_company_id"), table_name="sync_operations")
    op.drop_table("sync_operations")
    op.drop_index("ix_cash_sessions_device_opened", table_name="cash_sessions")
    op.drop_index("ix_cash_sessions_company_sync", table_name="cash_sessions")
    op.drop_index(op.f("ix_cash_sessions_company_id"), table_name="cash_sessions")
    op.drop_index(op.f("ix_cash_sessions_branch_id"), table_name="cash_sessions")
    op.drop_table("cash_sessions")
    op.drop_index("ix_payment_methods_company_sync", table_name="payment_methods")
    op.drop_index(op.f("ix_payment_methods_company_id"), table_name="payment_methods")
    op.drop_table("payment_methods")
    # ### end Alembic commands ###
