"""suppliers and purchasing

Revision ID: 34f69fa13fd1
Revises: 311a2c40e3d3
Create Date: 2026-09-25 22:41:16.189597+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "34f69fa13fd1"
down_revision: str | Sequence[str] | None = "311a2c40e3d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("contact_person", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("tin", sa.String(length=32), nullable=True),
        sa.Column("payment_terms_days", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_suppliers_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("company_id", "code", name=op.f("uq_suppliers_company_id_code")),
    )
    op.create_index(op.f("ix_suppliers_company_id"), "suppliers", ["company_id"], unique=False)
    op.create_index(op.f("ix_suppliers_name"), "suppliers", ["name"], unique=False)
    op.create_table(
        "purchase_orders",
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("stock_location_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="DRAFT", nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'APPROVED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CLOSED', 'CANCELLED')",
            name=op.f("ck_purchase_orders_status"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"], ["users.id"], name=op.f("fk_purchase_orders_approved_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_purchase_orders_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_purchase_orders_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_purchase_orders_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["stock_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_purchase_orders_stock_location_id_stock_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_purchase_orders_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
        sa.UniqueConstraint(
            "company_id", "number", name=op.f("uq_purchase_orders_company_id_number")
        ),
    )
    op.create_index(
        op.f("ix_purchase_orders_branch_id"), "purchase_orders", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_company_id"), "purchase_orders", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_supplier_id"), "purchase_orders", ["supplier_id"], unique=False
    )
    op.create_table(
        "goods_receipts",
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=True),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("stock_location_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_invoice_no", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("received_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_goods_receipts_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_goods_receipts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_goods_receipts_purchase_order_id_purchase_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["received_by_id"], ["users.id"], name=op.f("fk_goods_receipts_received_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["stock_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_goods_receipts_stock_location_id_stock_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_goods_receipts_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipts")),
        sa.UniqueConstraint(
            "company_id", "number", name=op.f("uq_goods_receipts_company_id_number")
        ),
    )
    op.create_index(
        op.f("ix_goods_receipts_branch_id"), "goods_receipts", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipts_company_id"), "goods_receipts", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipts_purchase_order_id"),
        "goods_receipts",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_goods_receipts_supplier_id"), "goods_receipts", ["supplier_id"], unique=False
    )
    op.create_table(
        "purchase_order_lines",
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("unit_factor", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "received_base_quantity",
            sa.Numeric(precision=14, scale=3),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_order_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_purchase_order_lines_unit_cost_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_purchase_order_lines_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_unit_id"],
            ["product_units.id"],
            name=op.f("fk_purchase_order_lines_product_unit_id_product_units"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_purchase_order_lines_purchase_order_id_purchase_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_purchase_order_lines_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_lines")),
        sa.UniqueConstraint(
            "purchase_order_id",
            "line_no",
            name=op.f("uq_purchase_order_lines_purchase_order_id_line_no"),
        ),
    )
    op.create_index(
        op.f("ix_purchase_order_lines_company_id"),
        "purchase_order_lines",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_lines_purchase_order_id"),
        "purchase_order_lines",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "goods_receipt_lines",
        sa.Column("goods_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("purchase_order_line_id", sa.Uuid(), nullable=True),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("base_unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("lot_no", sa.String(length=64), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_goods_receipt_lines_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_goods_receipt_lines_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["goods_receipt_id"],
            ["goods_receipts.id"],
            name=op.f("fk_goods_receipt_lines_goods_receipt_id_goods_receipts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_unit_id"],
            ["product_units.id"],
            name=op.f("fk_goods_receipt_lines_product_unit_id_product_units"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_line_id"],
            ["purchase_order_lines.id"],
            name=op.f("fk_goods_receipt_lines_purchase_order_line_id_purchase_order_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_goods_receipt_lines_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipt_lines")),
        sa.UniqueConstraint(
            "goods_receipt_id",
            "line_no",
            name=op.f("uq_goods_receipt_lines_goods_receipt_id_line_no"),
        ),
    )
    op.create_index(
        op.f("ix_goods_receipt_lines_company_id"),
        "goods_receipt_lines",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_goods_receipt_lines_goods_receipt_id"),
        "goods_receipt_lines",
        ["goods_receipt_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_goods_receipt_lines_goods_receipt_id"), table_name="goods_receipt_lines")
    op.drop_index(op.f("ix_goods_receipt_lines_company_id"), table_name="goods_receipt_lines")
    op.drop_table("goods_receipt_lines")
    op.drop_index(
        op.f("ix_purchase_order_lines_purchase_order_id"), table_name="purchase_order_lines"
    )
    op.drop_index(op.f("ix_purchase_order_lines_company_id"), table_name="purchase_order_lines")
    op.drop_table("purchase_order_lines")
    op.drop_index(op.f("ix_goods_receipts_supplier_id"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_purchase_order_id"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_company_id"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_branch_id"), table_name="goods_receipts")
    op.drop_table("goods_receipts")
    op.drop_index(op.f("ix_purchase_orders_supplier_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_company_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_branch_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(op.f("ix_suppliers_name"), table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_company_id"), table_name="suppliers")
    op.drop_table("suppliers")
    # ### end Alembic commands ###
