"""receipt journal

Revision ID: fbaf8685d085
Revises: 5f5a4551ceb3
Create Date: 2026-09-26 08:06:11.417699+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.shared import ddl

revision: str = "fbaf8685d085"
down_revision: str | Sequence[str] | None = "5f5a4551ceb3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipts",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("sale_id", sa.Uuid(), nullable=True),
        sa.Column("return_id", sa.Uuid(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("width", sa.SmallInteger(), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cashier_name", sa.String(length=200), nullable=False),
        sa.Column("reconstructed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(kind = 'SALE' AND sale_id IS NOT NULL) OR (kind = 'RETURN' AND return_id IS NOT NULL)",
            name=op.f("ck_receipts_kind_reference"),
        ),
        sa.CheckConstraint("width IN (58, 80)", name=op.f("ck_receipts_width_valid")),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_receipts_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_receipts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_receipts_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["return_id"], ["returns.id"], name=op.f("fk_receipts_return_id_returns")
        ),
        sa.ForeignKeyConstraint(["sale_id"], ["sales.id"], name=op.f("fk_receipts_sale_id_sales")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        sa.UniqueConstraint(
            "device_id", "kind", "number", name=op.f("uq_receipts_device_id_kind_number")
        ),
    )
    op.create_index(op.f("ix_receipts_company_id"), "receipts", ["company_id"], unique=False)
    op.create_index(
        "ix_receipts_company_issued", "receipts", ["company_id", "issued_at"], unique=False
    )
    op.create_index(op.f("ix_receipts_device_id"), "receipts", ["device_id"], unique=False)
    op.create_index(op.f("ix_receipts_return_id"), "receipts", ["return_id"], unique=False)
    op.create_index(op.f("ix_receipts_sale_id"), "receipts", ["sale_id"], unique=False)
    op.create_table(
        "receipt_prints",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("printed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("is_reprint", sa.Boolean(), nullable=False),
        sa.Column("fallback_reason", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_receipt_prints_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_receipt_prints_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["receipts.id"], name=op.f("fk_receipt_prints_receipt_id_receipts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_prints")),
    )
    op.create_index(
        op.f("ix_receipt_prints_company_id"), "receipt_prints", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_receipt_prints_receipt_id"), "receipt_prints", ["receipt_id"], unique=False
    )
    # ### end Alembic commands ###
    # The journal is append-only: receipts as issued, prints as they happened.
    for table in ("receipts", "receipt_prints"):
        op.execute(ddl.append_only_trigger(table))


def downgrade() -> None:
    for table in ("receipts", "receipt_prints"):
        op.execute(ddl.drop_append_only_trigger(table))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipt_prints_receipt_id"), table_name="receipt_prints")
    op.drop_index(op.f("ix_receipt_prints_company_id"), table_name="receipt_prints")
    op.drop_table("receipt_prints")
    op.drop_index(op.f("ix_receipts_sale_id"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_return_id"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_device_id"), table_name="receipts")
    op.drop_index("ix_receipts_company_issued", table_name="receipts")
    op.drop_index(op.f("ix_receipts_company_id"), table_name="receipts")
    op.drop_table("receipts")
    # ### end Alembic commands ###
