"""inventory documents

Revision ID: 311a2c40e3d3
Revises: 43cc34f6bf79
Create Date: 2026-09-25 22:37:59.326559+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "311a2c40e3d3"
down_revision: str | Sequence[str] | None = "43cc34f6bf79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_adjustments",
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("stock_location_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_stock_adjustments_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_stock_adjustments_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_stock_adjustments_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["stock_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_stock_adjustments_stock_location_id_stock_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_adjustments")),
    )
    op.create_index(
        "ix_stock_adjustments_company_created",
        "stock_adjustments",
        ["company_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_adjustments_company_id"), "stock_adjustments", ["company_id"], unique=False
    )
    op.create_table(
        "stock_counts",
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("stock_location_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="IN_PROGRESS", nullable=False),
        sa.Column("is_full", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("started_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_by_id", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('IN_PROGRESS', 'COMPLETED', 'CANCELLED')",
            name=op.f("ck_stock_counts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_stock_counts_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_stock_counts_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_id"], ["users.id"], name=op.f("fk_stock_counts_completed_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["started_by_id"], ["users.id"], name=op.f("fk_stock_counts_started_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["stock_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_stock_counts_stock_location_id_stock_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_counts")),
    )
    op.create_index(op.f("ix_stock_counts_branch_id"), "stock_counts", ["branch_id"], unique=False)
    op.create_index(
        op.f("ix_stock_counts_company_id"), "stock_counts", ["company_id"], unique=False
    )
    op.create_table(
        "stock_transfers",
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("from_location_id", sa.Uuid(), nullable=False),
        sa.Column("to_location_id", sa.Uuid(), nullable=False),
        sa.Column("from_branch_id", sa.Uuid(), nullable=False),
        sa.Column("to_branch_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="DRAFT", nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_by_id", sa.Uuid(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_by_id", sa.Uuid(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'IN_TRANSIT', 'RECEIVED', 'CANCELLED')",
            name=op.f("ck_stock_transfers_status"),
        ),
        sa.CheckConstraint(
            "from_location_id <> to_location_id",
            name=op.f("ck_stock_transfers_different_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_stock_transfers_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_stock_transfers_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["from_branch_id"],
            ["branches.id"],
            name=op.f("fk_stock_transfers_from_branch_id_branches"),
        ),
        sa.ForeignKeyConstraint(
            ["from_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_stock_transfers_from_location_id_stock_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["received_by_id"], ["users.id"], name=op.f("fk_stock_transfers_received_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["sent_by_id"], ["users.id"], name=op.f("fk_stock_transfers_sent_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["to_branch_id"], ["branches.id"], name=op.f("fk_stock_transfers_to_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["to_location_id"],
            ["stock_locations.id"],
            name=op.f("fk_stock_transfers_to_location_id_stock_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfers")),
    )
    op.create_index(
        op.f("ix_stock_transfers_company_id"), "stock_transfers", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transfers_from_branch_id"),
        "stock_transfers",
        ["from_branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_to_branch_id"), "stock_transfers", ["to_branch_id"], unique=False
    )
    op.create_table(
        "stock_adjustment_lines",
        sa.Column("adjustment_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("movement_type", sa.String(length=24), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "movement_type IN ('ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'DAMAGED', 'EXPIRED')",
            name=op.f("ck_stock_adjustment_lines_movement_type"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_stock_adjustment_lines_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_id"],
            ["stock_adjustments.id"],
            name=op.f("fk_stock_adjustment_lines_adjustment_id_stock_adjustments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_stock_adjustment_lines_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_unit_id"],
            ["product_units.id"],
            name=op.f("fk_stock_adjustment_lines_product_unit_id_product_units"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_stock_adjustment_lines_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_adjustment_lines")),
    )
    op.create_index(
        op.f("ix_stock_adjustment_lines_adjustment_id"),
        "stock_adjustment_lines",
        ["adjustment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_adjustment_lines_company_id"),
        "stock_adjustment_lines",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "stock_count_lines",
        sa.Column("stock_count_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("counted_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("system_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("variance", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("counted_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "counted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "counted_quantity >= 0", name=op.f("ck_stock_count_lines_counted_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_stock_count_lines_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["counted_by_id"], ["users.id"], name=op.f("fk_stock_count_lines_counted_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["stock_count_id"],
            ["stock_counts.id"],
            name=op.f("fk_stock_count_lines_stock_count_id_stock_counts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_stock_count_lines_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_count_lines")),
        sa.UniqueConstraint(
            "stock_count_id",
            "variant_id",
            name=op.f("uq_stock_count_lines_stock_count_id_variant_id"),
        ),
    )
    op.create_index(
        op.f("ix_stock_count_lines_company_id"), "stock_count_lines", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_count_lines_stock_count_id"),
        "stock_count_lines",
        ["stock_count_id"],
        unique=False,
    )
    op.create_table(
        "stock_transfer_lines",
        sa.Column("transfer_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("product_unit_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("received_base_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_transfer_lines_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_stock_transfer_lines_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_unit_id"],
            ["product_units.id"],
            name=op.f("fk_stock_transfer_lines_product_unit_id_product_units"),
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["stock_transfers.id"],
            name=op.f("fk_stock_transfer_lines_transfer_id_stock_transfers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_stock_transfer_lines_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfer_lines")),
    )
    op.create_index(
        op.f("ix_stock_transfer_lines_company_id"),
        "stock_transfer_lines",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfer_lines_transfer_id"),
        "stock_transfer_lines",
        ["transfer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_transfer_lines_transfer_id"), table_name="stock_transfer_lines")
    op.drop_index(op.f("ix_stock_transfer_lines_company_id"), table_name="stock_transfer_lines")
    op.drop_table("stock_transfer_lines")
    op.drop_index(op.f("ix_stock_count_lines_stock_count_id"), table_name="stock_count_lines")
    op.drop_index(op.f("ix_stock_count_lines_company_id"), table_name="stock_count_lines")
    op.drop_table("stock_count_lines")
    op.drop_index(op.f("ix_stock_adjustment_lines_company_id"), table_name="stock_adjustment_lines")
    op.drop_index(
        op.f("ix_stock_adjustment_lines_adjustment_id"), table_name="stock_adjustment_lines"
    )
    op.drop_table("stock_adjustment_lines")
    op.drop_index(op.f("ix_stock_transfers_to_branch_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_from_branch_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_company_id"), table_name="stock_transfers")
    op.drop_table("stock_transfers")
    op.drop_index(op.f("ix_stock_counts_company_id"), table_name="stock_counts")
    op.drop_index(op.f("ix_stock_counts_branch_id"), table_name="stock_counts")
    op.drop_table("stock_counts")
    op.drop_index(op.f("ix_stock_adjustments_company_id"), table_name="stock_adjustments")
    op.drop_index("ix_stock_adjustments_company_created", table_name="stock_adjustments")
    op.drop_table("stock_adjustments")
    # ### end Alembic commands ###
