"""sc pwd discount and bir fields

Revision ID: e1c3cb7b756c
Revises: ff379da3c120
Create Date: 2026-09-26 04:19:05.520388+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e1c3cb7b756c"
down_revision: str | Sequence[str] | None = "ff379da3c120"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("vat_registered", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.add_column(
        "companies", sa.Column("bir_accreditation_no", sa.String(length=64), nullable=True)
    )
    op.add_column("devices", sa.Column("bir_min", sa.String(length=32), nullable=True))
    op.add_column("devices", sa.Column("bir_serial_number", sa.String(length=64), nullable=True))
    op.add_column("devices", sa.Column("bir_ptu_number", sa.String(length=64), nullable=True))
    op.add_column("devices", sa.Column("bir_ptu_issued_on", sa.Date(), nullable=True))
    op.add_column(
        "products",
        sa.Column("sc_pwd_eligible", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "sale_items",
        sa.Column("statutory", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "sale_items",
        sa.Column(
            "vat_exemption",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "sale_items",
        sa.Column(
            "statutory_discount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column("sales", sa.Column("statutory_kind", sa.String(length=8), nullable=True))
    op.add_column("sales", sa.Column("statutory_id_number", sa.String(length=64), nullable=True))
    op.add_column("sales", sa.Column("statutory_holder_name", sa.String(length=200), nullable=True))
    op.add_column("sales", sa.Column("statutory_holder_tin", sa.String(length=32), nullable=True))
    op.add_column(
        "sales",
        sa.Column(
            "vat_exemption_total",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "sales",
        sa.Column(
            "statutory_discount_total",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales", "statutory_discount_total")
    op.drop_column("sales", "vat_exemption_total")
    op.drop_column("sales", "statutory_holder_tin")
    op.drop_column("sales", "statutory_holder_name")
    op.drop_column("sales", "statutory_id_number")
    op.drop_column("sales", "statutory_kind")
    op.drop_column("sale_items", "statutory_discount")
    op.drop_column("sale_items", "vat_exemption")
    op.drop_column("sale_items", "statutory")
    op.drop_column("products", "sc_pwd_eligible")
    op.drop_column("devices", "bir_ptu_issued_on")
    op.drop_column("devices", "bir_ptu_number")
    op.drop_column("devices", "bir_serial_number")
    op.drop_column("devices", "bir_min")
    op.drop_column("companies", "bir_accreditation_no")
    op.drop_column("companies", "vat_registered")
    # ### end Alembic commands ###
