"""expenses and report exports

Revision ID: c5a1c4ea7bf5
Revises: 428f5d187452
Create Date: 2026-09-25 22:52:30.906621+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c5a1c4ea7bf5"
down_revision: str | Sequence[str] | None = "428f5d187452"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EXPENSE_CATEGORIES = [
    "Rent",
    "Utilities",
    "Salaries",
    "Supplies",
    "Transportation",
    "Repairs & Maintenance",
    "Taxes & Licenses",
    "Other",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_expense_categories_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_categories")),
        sa.UniqueConstraint(
            "company_id", "name", name=op.f("uq_expense_categories_company_id_name")
        ),
    )
    op.create_index(
        op.f("ix_expense_categories_company_id"), "expense_categories", ["company_id"], unique=False
    )
    op.create_table(
        "report_exports",
        sa.Column("report", sa.String(length=64), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("requested_by_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'DONE', 'FAILED')",
            name=op.f("ck_report_exports_status"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_report_exports_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"], ["users.id"], name=op.f("fk_report_exports_requested_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_exports")),
    )
    op.create_index(
        op.f("ix_report_exports_company_id"), "report_exports", ["company_id"], unique=False
    )
    op.create_table(
        "expenses",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("paid_from", sa.String(length=16), nullable=False),
        sa.Column("payee", sa.String(length=200), nullable=True),
        sa.Column("reference_no", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("cash_movement_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "paid_from IN ('CASH_DRAWER', 'PETTY_CASH', 'BANK', 'EWALLET', 'OTHER')",
            name=op.f("ck_expenses_paid_from"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_expenses_amount_positive")),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_expenses_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["cash_movement_id"],
            ["cash_movements.id"],
            name=op.f("fk_expenses_cash_movement_id_cash_movements"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["expense_categories.id"],
            name=op.f("fk_expenses_category_id_expense_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_expenses_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"], ["users.id"], name=op.f("fk_expenses_recorded_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_id"], ["users.id"], name=op.f("fk_expenses_voided_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
    )
    op.create_index(op.f("ix_expenses_branch_id"), "expenses", ["branch_id"], unique=False)
    op.create_index(
        "ix_expenses_company_date", "expenses", ["company_id", "expense_date"], unique=False
    )
    op.create_index(op.f("ix_expenses_company_id"), "expenses", ["company_id"], unique=False)
    # ### end Alembic commands ###

    # Default expense categories for companies created before this migration.
    for name in EXPENSE_CATEGORIES:
        op.execute(
            sa.text(
                "INSERT INTO expense_categories (id, company_id, name) "
                "SELECT gen_random_uuid(), id, :name FROM companies ON CONFLICT DO NOTHING"
            ).bindparams(name=name)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expenses_company_id"), table_name="expenses")
    op.drop_index("ix_expenses_company_date", table_name="expenses")
    op.drop_index(op.f("ix_expenses_branch_id"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_report_exports_company_id"), table_name="report_exports")
    op.drop_table("report_exports")
    op.drop_index(op.f("ix_expense_categories_company_id"), table_name="expense_categories")
    op.drop_table("expense_categories")
    # ### end Alembic commands ###
